name: user_list
description: Test Flutter project.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^7.5.0
  fast_immutable_collections: ^9.1.5

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  universal_html: ^2.2.3

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
