name: user_list
description: Test Flutter project.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^7.5.0
  
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.5
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5 

flutter:
  uses-material-design: true
